DROP SEQUENCE UKRAINIANSTREETS.REGIONS_SEQ;

CREATE SEQUENCE UKRAINIANSTREETS.REGIONS_SEQ
  START WITH 25
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE UKRAINIANSTREETS.DISTRICTS_SEQ;

CREATE SEQUENCE UKRAINIANSTREETS.DISTRICTS_SEQ
  START WITH 460
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE UKRAINIANSTREETS.LOCALITIES_SEQ;

CREATE SEQUENCE UKRAINIANSTREETS.LOCALITIES_SEQ
  START WITH 24064
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE UKRAINIANSTREETS.STREETS_SEQ;

CREATE SEQUENCE UKRAINIANSTREETS.STREETS_SEQ
  START WITH 104886
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

ALTER TABLE UKRAINIANSTREETS.REGIONS
 DROP PRIMARY KEY CASCADE;

DROP TABLE UKRAINIANSTREETS.REGIONS CASCADE CONSTRAINTS;

CREATE TABLE UKRAINIANSTREETS.REGIONS
(
  ID             NUMBER                         NOT NULL,
  OVERPASS_ID    NUMBER                         NOT NULL,
  NAME           VARCHAR2(256 BYTE),
  OVERPASS_TYPE  VARCHAR2(100 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index UKRAINIANSTREETS.SYS_C00230153.
--  The object is created when the parent object is created.

CREATE OR REPLACE TRIGGER UKRAINIANSTREETS.REGIONS_BEF_INS_TRG
   BEFORE INSERT
   ON UKRAINIANSTREETS.REGIONS
   FOR EACH ROW
BEGIN
   IF :NEW.ID IS NULL OR :NEW.ID = 0
   THEN
      SELECT REGIONS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
   END IF;
END;
/


ALTER TABLE UKRAINIANSTREETS.REGIONS ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE UKRAINIANSTREETS.DISTRICTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE UKRAINIANSTREETS.DISTRICTS CASCADE CONSTRAINTS;

CREATE TABLE UKRAINIANSTREETS.DISTRICTS
(
  ID             NUMBER                         NOT NULL,
  REGION_ID      NUMBER,
  OVERPASS_ID    NUMBER                         NOT NULL,
  NAME           VARCHAR2(256 BYTE),
  OVERPASS_TYPE  VARCHAR2(100 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index UKRAINIANSTREETS.SYS_C00232540.
--  The object is created when the parent object is created.

CREATE OR REPLACE TRIGGER UKRAINIANSTREETS.DISTRICTS_BEF_INS_TRG
   BEFORE INSERT
   ON UKRAINIANSTREETS.DISTRICTS
   FOR EACH ROW
BEGIN
   IF :NEW.ID IS NULL OR :NEW.ID = 0
   THEN
      SELECT DISTRICTS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
   END IF;
END;
/


ALTER TABLE UKRAINIANSTREETS.DISTRICTS ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE UKRAINIANSTREETS.LOCALITIES
 DROP PRIMARY KEY CASCADE;

DROP TABLE UKRAINIANSTREETS.LOCALITIES CASCADE CONSTRAINTS;

CREATE TABLE UKRAINIANSTREETS.LOCALITIES
(
  ID             NUMBER                         NOT NULL,
  DISTRICT_ID    NUMBER,
  OVERPASS_ID    NUMBER                         NOT NULL,
  NAME           VARCHAR2(256 BYTE),
  OVERPASS_TYPE  VARCHAR2(100 BYTE),
  LOCALITY_TYPE  VARCHAR2(100 BYTE),
  REGION_ID      NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index UKRAINIANSTREETS.SYS_C00230162.
--  The object is created when the parent object is created.

CREATE OR REPLACE TRIGGER UKRAINIANSTREETS.LOCALITYS_BEF_INS_TRG
   BEFORE INSERT
   ON UKRAINIANSTREETS.LOCALITIES
   FOR EACH ROW
BEGIN
   IF :NEW.ID IS NULL OR :NEW.ID = 0
   THEN
      SELECT LOCALITIES_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
   END IF;
END;
/


ALTER TABLE UKRAINIANSTREETS.LOCALITIES ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE UKRAINIANSTREETS.STREETS
 DROP PRIMARY KEY CASCADE;

DROP TABLE UKRAINIANSTREETS.STREETS CASCADE CONSTRAINTS;

CREATE TABLE UKRAINIANSTREETS.STREETS
(
  ID             NUMBER                         NOT NULL,
  OVERPASS_ID    NUMBER                         NOT NULL,
  LOCALITY_ID    NUMBER,
  NAME           VARCHAR2(256 BYTE),
  OVERPASS_TYPE  VARCHAR2(100 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index UKRAINIANSTREETS.SYS_C00230168.
--  The object is created when the parent object is created.

CREATE OR REPLACE TRIGGER UKRAINIANSTREETS.STREETS_BEF_INS_TRG
   BEFORE INSERT
   ON UKRAINIANSTREETS.STREETS
   FOR EACH ROW
BEGIN
   IF :NEW.ID IS NULL OR :NEW.ID = 0
   THEN
      SELECT STREETS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
   END IF;
END;
/


ALTER TABLE UKRAINIANSTREETS.STREETS ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);